#!/bin/bash
#####################################Server Hardening Script################################
red='\e[0;31m'
blue='\e[0;34m'
green='\e[0;32m'
yellow='\e[0;33m'
NC='\e[0m' # No Color
blink='\e[0;5m'

selinux() {
printf "%-50s\t   " "Selinux Configuration"
grep SELINUX=enforcing /etc/sysconfig/selinux &> /dev/null
if [ $? -eq 0 ]
	then
		sed -i s/SELINUX=enforcing/SELINUX=disabled/ /etc/sysconfig/selinux
		sed -i s/SELINUX=enforcing/SELINUX=disabled/ /etc/selinux/config
		echo -e "[\e[32m Done \e[0m]"
	else
		echo -e "$green already disabled $NC"
fi
}

disable_root(){ 
printf "%-50s\t   " "Disabling ssh root login"
sleep 2

if [ ! -f /etc/ssh/sshd_config-org ]; then
	cp /etc/ssh/sshd_config /etc/ssh/sshd_config-org
fi

echo -e "\n###Added SSH Root Restriction by Security Hardening Auto Script ###" >> /etc/ssh/sshd_config
echo -e "[\e[32m Done \e[0m]"

echo "PermitRootLogin no" >> /etc/ssh/sshd_config
echo "PasswordAuthentication yes" >> /etc/ssh/sshd_config
echo "ClientAliveInterval 900" >> /etc/ssh/sshd_config
echo "Banner  /etc/banner"   >> /etc/ssh/sshd_config 
/etc/init.d/sshd reload
}

console_tty() {
printf "%-50s\t   " "Disabling root login to Console and tty"
sleep 2

if [ ! -f /etc/securetty-org ]; then
	cp /etc/securetty /etc/securetty-org
fi

cp /etc/securetty /etc/securetty-org
cat > /etc/securetty << 'EOF'  
console
tty1
tty2
tty3
tty4
tty5
tty6
EOF
echo -e "[\e[32m Done \e[0m]"
}

password_policy() {
printf "%-50s\t   " "Setting Password Policy"
sleep 2
if [ ! -f /etc/login.defs-org ]; then
cp   /etc/login.defs /etc/login.defs-org
fi

sed -i s/"PASS_MAX_DAYS\t99999"/"PASS_MAX_DAYS\t60"/ /etc/login.defs
sed -i s/"PASS_MIN_DAYS\t0"/"PASS_MIN_DAYS\t7"/ /etc/login.defs
sed -i s/"PASS_MIN_LEN\t5"/"PASS_MIN_LEN\t8"/ /etc/login.defs
echo -e "[\e[32m Done \e[0m]"
}

ntp() {
printf "%-50s\t   " "NTP Confifuration"
sleep 2
rpm -qa |grep -w ntp &> /dev/null
if [ $? -ne 0 ]
	then 
		yum install ntp -y &> /dev/null
fi
if [ ! -f /etc/ntp.conf-org ]; then
cp   /etc/ntp.conf /etc/ntp.conf-org
fi
echo "server ntp.newsint.co.uk"  > /etc/ntp.conf
echo -e "[\e[32m Done \e[0m]"
}

log_rota() {
printf "%-50s\t   " "Setting sudoer log rotation"
cat > /etc/logrotate.d/sudoer << 'EOF'
/var/log/sudoer
 {
    weekly
    rotate 52
    compress
    maxage 365
    size=51200k
    notifempty
    missingok
    copytruncate
 }
EOF
echo -e "[\e[32m Done \e[0m]"
}

dns() {
printf "%-50s\t   " "DNS Client Configuration"
sleep 2

if [ ! -f /etc/resolv.conf-org ]; then
cp   /etc/resolv.conf /etc/resolv.conf-org
fi

ldap_client() {
printf "%-50s\t   " "LDAP Client Configuration"
sleep 2

if [ ! -f /etc/ldap.conf-org ]; then
cp   /etc/ldap.conf /etc/ldap.conf-org
fi

user() {
id -a sysmaintain  &> /dev/null
if [ $? -ne 0 ] 
then
useradd -u 59028  -c "Local sysadmin User" sysmaintain
fi

if [ ! -d /home/sysmaintain/.ssh ]; then
mkdir /home/sysmaintain/.ssh
fi
chmod 700 /home/sysmaintain/.ssh
chown sysmaintain:sysmaintain /home/sysmaintain/.ssh
cat > /home/sysmaintain/.ssh/authorized_keys << 'EOF'
ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAo+5fQJz5l65sNtjifeiXZZJaY8F+0HPLlX+sNqc+rwd0HLmYmnCRZAOqgths5QWCGDo8d1OlKj4xGeonI2gNVVwsvCVlugqjcQ9dtpKegT30wBdqHTP72DMQCOJS2iwVMG0O8GBgV1TOFIBg8XzV6HsihnngdHBRo1sEf3YKtNtYb5Gk2qYFAxdYCDVrBgoZc/4cNEraRms2t3qgAWdLvGihItyypvbHs3B5l5XW2dv4WUmI9LDuXrJXRXflmGd5IMyoDooXANmrz+Q8zFx1myY660MtMb/pKvR9mnHKuR70JFpMTZdEAnsxh6kC7tInmvGKZvY6kHvL8pjFd==
EOF
chmod 600 /home/sysmaintain/.ssh/authorized_keys
chown sysmaintain:sysmaintain /home/sysmaintain/.ssh/authorized_keys
}

iounix() {
printf "%-50s\t   " "Adding IOunixnotify Script"
sleep 2

cat > /etc/init.d/IOunixnotify << 'EOF'
#!/bin/sh
# chkconfig: 345 90 10
# description: Runs the  IOunixnotify script Application Server
# processname: IOunixnotify

#       Alert IOUNIX that somebody has rebooted

MAILTO="vijay.240385@gmail.com"

# Start/stop

case "$1" in
'start')

                echo "Alerting $MAILTO of reboot"
                echo "`uname -n` rebooting is done at `date` '\n' `uptime`"| mailx -s "`uname -n` rebooting is done at `date`" $MAILTO

        ;;

'stop')
                echo "Alerting $MAILTO of reboot"
                echo "`uname -n` rebooting at `date` '\n' `uptime`"| mailx -s "`uname -n` rebooting at `date`" $MAILTO


        ;;
*)
        echo "Usage: `basename $0` start|stop"
        ;;
esac
exit 0
EOF
chmod +x /etc/init.d/IOunixnotify
ln -s /etc/init.d/IOunixnotify /etc/rc3.d/K01IOunixnotify
ln -s /etc/init.d/IOunixnotify /etc/rc3.d/S99IOunixnotify
chkconfig --add IOunixnotify
chkconfig --level 35 IOunixnotify on
chkconfig --level 01246 IOunixnotify off
chkconfig sendmail off
echo -e "[\e[32m Done \e[0m]"
}
disable_ipv6() {
printf "%-50s\t   " "Disabling IPv6"
echo  "127.0.0.1  localhost.localdomain  localhost" > /etc/hosts
echo -e "[\e[32m Done \e[0m]"
}

disable_service() {
printf "%-50s\t   " "Disabling unwanted services"
sleep 2
chkconfig anacron off;chkconfig haldaemon off; chkconfig messagebus off; chkconfig hidd off; chkconfig microcode_ctl off; chkconfig pcscd off; chkconfig avahi-daemon off; chkconfig readahead_early off; chkconfig bluetooth off; chkconfig readahead_later off; chkconfig kudzu off; chkconfig firstboot off; chkconfig mcstrans off; chkconfig setroubleshoot off; chkconfig gpm off; chkconfig mdmonitor off; chkconfig xfs off; chkconfig sendmail off; chkconfig yum-updatesd off ; chkconfig iscsi off; chkconfig iscsid off; chkconfig atd off; chkconfig iptables off; chkconfig ip6tables off; chkconfig auditd off; chkconfig restorecond off; chkconfig smartd off; 
echo -e "[\e[32m Done \e[0m]"
}

##################Main Programme############################################
clear
echo "                                                    "
echo "===================================================="
echo "RHEL 5 Server Hardening Process 			  "
echo "===================================================="
echo "                                                    "
echo -e "$blue 	1) Selinux Status $NC "
echo -e "$blue 	2) Disabling ssh root login $NC "
echo -e "$blue 	3) Disabling root login to Console and tty $NC "
echo -e "$blue 	4) Setting Password Policy $NC "
echo -e "$blue 	5) NTP Confifuration $NC "
echo -e "$blue 	6) Setting sudoer log rotation $NC "
echo -e "$blue 	7) DNS Client Configuration $NC "
echo -e "$blue 	8) LDAP Client Configuration $NC "
echo -e "$blue 	9) Mail Relay Configuartion $NC "
echo -e "$blue 	10) Adding IOunixnotify Script $NC "
echo -e "$blue 	11) Disabling IPv6 $NC "
echo -e "$blue	12) Disabling unwanted services $NC "
echo -e "$blue 	13) All $NC"
echo -e	"$red	X) Exit $NC"
echo "                                                    "
while true; do
echo "===================================================="
echo -ne "$yellow Enter the choice you want to proceed with:$NC   "
read RHEL

case $RHEL in
	1)selinux ;;
	2) user ; disable_root ;;
	3)console_tty ;;
	4)password_policy ;;
	5)ntp ;;
	6)log_rota ;;
	7)dns ;;
	8)ldap_client ;;
	9)mail_relay ;;
	10)iounix ;;
	11)disable_ipv6 ;;
	12)disable_service ;;
	13)disable_root;console_tty; password_policy; ntp; log_rota; dns; ldap_client; mail_relay; iounix; disable_ipv6; disable_service ;;
	[Xx]) exit 0 ;;
        *) echo "Enter correct Key"
	exit 1 ;;
esac
done
